#!/bin/sh
dwmblocks &
xrdb ~/.Xresources
xwallpaper --zoom ~/Pictures/wallpaper.jpg
xinput --set-prop 9 'libinput Accel Profile Enabled' 0, 1
xmodmap -e 'clear Lock'
xmodmap -e 'keycode 0x42=Escape'
dwm
